version: '3.9'

services:
  keycloak:
    hostname: keycloak
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-Keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres

  web:
    hostname: website
    container_name: website
    build:
      context: ./nextjs-oauth2-example
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:15
    restart: always
    shm_size: 128mb
    volumes:
      - ./sqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
